name: Build Test

on:
  push:
    branches:
    - MiraiCQ-Cli
    paths:
    - src/**

jobs:
  test:
    name: build project
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup VS2019
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild
      working-directory: src/MiraiCQ
      run: msbuild /property:Configuration=Release
    - name: upload file
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: 
            src/MiraiCQ/Release/
            !src/MiraiCQ/Release/*.exp
            !src/MiraiCQ/Release/*.lib
            !src/MiraiCQ/Release/*.pdb
